[project]
name = "mishka-dreamer"
version = "0.1.0"
description = "Consolidates and cleanups memory"
requires-python = ">=3.11"
dependencies = [
    "httpx",
    "apscheduler",
    "loguru",
    "numpy",
    "python-dotenv",
    "fastapi",
    "uvicorn",
    "aio-pika"
]
